### PR TITLE
MAINT: Release script app bundles

### PR DESCRIPTION
**Pull request by gabrielbmotta**
- Build for Mac without app bundles

### CODE REVIEW

**Review by juangpc — APPROVED** [review]

**Comment by LorenzE** [comment]
@gabrielbmotta please check if macdeployqt still works on builds without app bundles.

**Review by juangpc — APPROVED** [review]

**Comment by LorenzE** [comment]
@juangpc did you check if macdeployqt likes these changes you just merged? Otherwise we are left with a broken CI ...

**Comment by LorenzE** [comment]
@juangpc @gabrielbmotta [Seems like macdeployqt does not like this](https://github.com/mne-tools/mne-cpp/runs/3144079371?check_suite_focus=true#step:9:12). There might be a way to configure macdeployqt to work on non app bundles though.

image

**Comment by juangpc** [comment]
sorry about that.

**Comment by LorenzE** [comment]
No worries. Any particular reason why we do not want to have app bundles in our releases. I am sure we can find a way to make the CI work without it. Depends on how much a priority this is for you.

**Pull request merged**
