### PR TITLE
[ENH] MNE Analyze - display info about file in signal viewer

### PR DESCRIPTION
**Pull request by gabrielbmotta**
- Display file info beneath signal viewer

### CODE REVIEW

**Comment by juangpc** [comment]
I like it a lot.

**Comment by LorenzE** [comment]
You can also have a look at the ChannelInfoModel. You can pass a fiffinfo to it and then visualize via a QTableView. It would give you channel wise information about the recording.

**Comment by juangpc** [comment]
> ChannelInfoModel

Like what kind of info? 

Thanks, you're on everything.

**Comment by LorenzE** [comment]
It basically shows you a table with channels as rows and columns as the fiff ch info (unit, location, bad channel status, etc)

**Review by juangpc — APPROVED** [review]

**Pull request merged**
