### PR TITLE
[ENH] Add BrainFlowBoard plugin to MNE-SCAN

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

Restore changes from #451 in new PR.

Also I changed sleeptimeout and now it should add ~10 values per one call
```
int iMinSamples = 10;
unsigned long lSamplingPeriod = (unsigned long)(1000000.0 / m_iSamplingRate) * iMinSamples;
```

### CODE REVIEW

**Comment by Andrey1994** [comment]
@LorenzE If its the only plugin everything works fine for me but if I create pipeline with signal processing algorithms looks like smth is wrong. Maybe it can be fixed in a separated PR.
And I still wanna add it to workflows later

**Comment by LorenzE** [comment]
thx @Andrey1994 I will take another look at it tomorrow.

**Comment by LorenzE** [comment]
Can you open the PR from a branch different from master please?

**Comment by Andrey1994** [comment]
sure, check #487

**Pull request closed without merging**
