### PR TITLE
[FIX] Fix path for brainflow libs

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by Andrey1994** [comment]
wierd but it didnt solve the issue on linux

**Comment by Andrey1994** [comment]
but Windows build is ok now

**Comment by Andrey1994** [comment]
@LorenzE lets try PATH and LD_LIBRARY_PATH env vars?

**Comment by LorenzE** [comment]
Either that or how about copying the lib files to the /lib instead of /bin folder? Also, I just realized that the MacOS changes I introduced did not work either. I will give the MacOS build another try later today.

**Comment by Andrey1994** [comment]
<< how about copying the lib files to the /lib instead of /bin folder?
These libs should be in searchpath in runtime, the easiest option for it - place them to the same folder where executable is located and I think its bin folder. But I have no idea what linudeployqt does if it handles it then lets place to lib folder instead. Or copy to both of them

**Pull request merged**
