### PR TITLE
Add ui files to CMakeLists so IDEs can show them

### PR DESCRIPTION
**Pull request by gabrielbmotta**
Add ui files to CMakeLists.txt in mnescan plugins and disp library so that IDEs (like QtCreator) will show them in the project view.

### CODE REVIEW

**Comment by juangpc** [comment]
Just pushed some minor edits, styling, space characters finishing lines, long lines, things of that nature.

**Review by juangpc — DISMISSED** [review]

**Comment by juangpc** [comment]
Whenever this is ready, or needs review again, do let me know

**Comment by gabrielbmotta** [comment]
> Just pushed some minor edits, styling, space characters finishing lines, long lines, things of that nature.

As much as I agree with some of the styling changes made, why are they being pushed to this PR? They are on completely separate files and concern different lines of the CMakeLists.txt, and do not affect ui files. And on top of that one of the changes to multiline commands broke the build because it was previously commented out and the new line added did not have a comment.

**Comment by juangpc** [comment]
> > Just pushed some minor edits, styling, space characters finishing lines, long lines, things of that nature.
> 
> As much as I agree with some of the styling changes made, why are they being pushed to this PR? They are on completely separate files and concern different lines of the CMakeLists.txt, and do not affect ui files. And on top of that one of the changes to multiline commands broke the build because it was previously commented out and the new line added did not have a comment.

Sorry about that. let me get back in a min

**Review by juangpc — APPROVED** [review]

**Comment by juangpc** [comment]
Ready on my side.

**Pull request merged**
