### PR TITLE
WIP [MAINT] Update CI linux runner version

### PR DESCRIPTION
**Pull request by gabrielbmotta**
- Update runners from 16.04 to 18.04. Unsure if minQt workflows running Qt 5.10 will like this.
- Might be a good time to discuss minimum requirements for compilers and OSs.

### CODE REVIEW

**Comment by juangpc** [comment]
interestingly it passed. in my ubuntu 18.04, repeating the qt binary script, and then trying to link and compile... failed. 

solved with : ``` sudo apt-get install libboost-all-dev```

**Comment by gabrielbmotta** [comment]
> interestingly it passed. in my ubuntu 18.04, repeating the qt binary script, and then trying to link and compile... failed. 
> 
> 
> 
> solved with : ``` sudo apt-get install libboost-all-dev```

That's not what solved it. I'm building Qt statically instead of downloading the static build from Dropbox, which was originally built on Ubuntu 16.

**Comment by juangpc** [comment]
> building Qt statically instead of downloading the static build from Dropbox
But that is exactly what I did. And it didn't link. Until I installed a 💩 load of libs with previous command. And then it finally worked.
Happy you got it working. Ubuntu's cis, are probably not exacly the same context as the one you could download from ubuntu's web as a fresh install.

**Comment by LorenzE** [comment]
@gabrielbmotta Thx for the effort! Seems like everything builds just fine except for the prebuilt static versions then? You can use this GH workflow to build and zip pre built static qt versions and download them as artifacts https://github.com/mne-tools/mne-cpp/blob/main/.github/workflows/buildqtbinaries.yml

**Comment by gabrielbmotta** [comment]
> > building Qt statically instead of downloading the static build from Dropbox
> > But that is exactly what I did. And it didn't link. Until I installed a 💩 load of libs with previous command. And then it finally worked.
> > Happy you got it working. Ubuntu's cis, are probably not exacly the same context as the one you could download from ubuntu's web as a fresh install.

Yeah, their ubuntu runner has a lot of [stuff pre-installed](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md)

**Comment by gabrielbmotta** [comment]
> @gabrielbmotta Thx for the effort! Seems like everything builds just fine except for the prebuilt static versions then? You can use this GH workflow to build and zip pre built static qt versions and download them as artifacts https://github.com/mne-tools/mne-cpp/blob/main/.github/workflows/buildqtbinaries.yml

The pullrequest.yml workflow seems to download these prebuilt static qt bundles from a dropbox link. Are these created with the buildqtbinaries.yml and then uploaded to dropbox? Is it your dropbox account?

**Comment by LorenzE** [comment]
> > @gabrielbmotta Thx for the effort! Seems like everything builds just fine except for the prebuilt static versions then? You can use this GH workflow to build and zip pre built static qt versions and download them as artifacts https://github.com/mne-tools/mne-cpp/blob/main/.github/workflows/buildqtbinaries.yml
> 
> The pullrequest.yml workflow seems to download these prebuilt static qt bundles from a dropbox link. Are these created with the buildqtbinaries.yml and then uploaded to dropbox? Is it your dropbox account?

Yes, they are stored on my dropbox. You can host them wherever you want until we find a more permanent mne-cpp storage.

**Comment by LorenzE** [comment]
@gabrielbmotta Since everything seems to compile under the new ubuntu, we would not need to change the minimum compiler and qt version. What do you think?

**Comment by LorenzE** [comment]
@gabrielbmotta we might have to deactivate some of the branch protection rules so this PR can be merged. After the merge we can then update the rules with the new workfow runs.

**Review by LorenzE — APPROVED** [review]

**Comment by gabrielbmotta** [comment]
> @gabrielbmotta we might have to deactivate some of the branch protection rules so this PR can be merged. After the merge we can then update the rules with the new workfow runs.

Ok. I've removed the rules that ran on ubuntu 16

**Pull request merged**
