### PR TITLE
[MAINT,ENH] Update brainflow

### PR DESCRIPTION
**Pull request by Andrey1994**
Signed-off-by: Andrey Parfenov <a1994ndrey@gmail.com>

### CODE REVIEW

**Comment by Andrey1994** [comment]
I dont get why pipeline failed...

**Comment by LorenzE** [comment]
> I dont get why pipeline failed...
This seems to be the problem: `brainflowboard.cpp:331:68: error: use of undeclared identifier 'UNSUPPORTED_BOARD_ERROR'`

**Comment by Andrey1994** [comment]
thanks, I didnt see this error in logs

**Comment by LorenzE** [comment]
> thanks, I didnt see this error in logs

Yeah, me neither. Somehow the github actions search function did not catch it. Had to rebuild locally.

**Pull request merged**
