### PR TITLE
Codecov yml

### PR DESCRIPTION
**Pull request by LorenzE**
Exclude include folder recursively

### CODE REVIEW

**Comment by LorenzE** [comment]
@jasmainak could you do another review/merge on this pls? Last PR apparently had no effect because I used a wrong syntax to ignore our include folder in codecov.yml

**Comment by jasmainak** [comment]
@LorenzE there is a merge commit in the history here. Is that fine?

**Comment by LorenzE** [comment]
Fixed the merge commit.

**Comment by juangpc** [comment]
Merging.

**Pull request merged**
